// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency_injection

import (
	"github.com/LouisTrezzini/foyer.enpc.org/app/services"
)

// Injectors from initialize.go:

func initializeContainer() (Container, error) {
	inMemoryAccountRepository := services.NewInMemoryAccountRepository()
	inMemoryDrinkRepository := services.NewInMemoryDrinkRepository()
	foyerServiceImpl := &services.FoyerServiceImpl{
		AccountRepository: inMemoryAccountRepository,
		DrinkRepository:   inMemoryDrinkRepository,
	}
	dependency_injectionContainer := Container{
		AccountRepository: inMemoryAccountRepository,
		DrinkRepository:   inMemoryDrinkRepository,
		FoyerService:      foyerServiceImpl,
	}
	return dependency_injectionContainer, nil
}
