// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency_injection

import (
	"github.com/LouisTrezzini/foyer.enpc.org/app/controllers"
	"github.com/LouisTrezzini/foyer.enpc.org/app/services"
)

// Injectors from initialize.go:

func initializeAccountController() (controllers.AccountController, error) {
	inMemoryAccountRepository := services.NewInMemoryAccountRepository()
	inMemoryDrinkRepository := services.NewInMemoryDrinkRepository()
	foyerServiceImpl := &services.FoyerServiceImpl{
		accountRepository: inMemoryAccountRepository,
		drinkRepository:   inMemoryDrinkRepository,
	}
	accountController := controllers.NewAccountController(inMemoryAccountRepository, foyerServiceImpl)
	return accountController, nil
}
