/*
 *
 * DrinksPage reducer
 *
 */

import { fromJS } from 'immutable';
import { DEFAULT_ACTION } from './constants';

export const initialState = fromJS({
  drinks: [
    {
      likes: 0,
      dislikes: 0,
      id: 22248,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Kro',
      slug: 'pinte-kro',
      type: 'beer',
      image_url: 'uploads/images/2315.jpeg',
      price: 1,
      alcohol: 4.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29169,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Carlsberg',
      slug: 'pinte-carlsberg',
      type: 'beer',
      image_url: 'uploads/images/4662.jpeg',
      price: 3.4,
      alcohol: 5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28971,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Saint Bernardus Triple',
      slug: 'saint-bernardus-triple',
      type: 'beer',
      image_url: 'uploads/images/4287.png',
      price: 2,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22275,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Triple Karmeliet',
      slug: 'triple-karmeliet',
      type: 'beer',
      image_url: 'uploads/images/2344.jpeg',
      price: 2.3,
      alcohol: 8.4,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22259,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Chouffe',
      slug: 'chouffe',
      type: 'beer',
      image_url: 'uploads/images/2327.png',
      price: 2.4,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28972,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Armand Ter Dolen',
      slug: 'armand-ter-dolen',
      type: 'beer',
      image_url: 'uploads/images/4288.jpeg',
      price: 2.2,
      alcohol: 7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29189,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Kasteel Rouge',
      slug: 'kasteel-rouge',
      type: 'beer',
      image_url: 'uploads/images/4676.jpeg',
      price: 2.1,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28895,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bouteille Cidre',
      slug: 'bouteille-cidre',
      type: 'beer',
      image_url: 'uploads/images/4251.jpeg',
      price: 3.2,
      alcohol: 5,
      volume: 0.75,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28970,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Belgoo Luppo',
      slug: 'belgoo-luppo',
      type: 'beer',
      image_url: 'uploads/images/4286.jpeg',
      price: 2.4,
      alcohol: 6.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22253,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Cuv\u00e9e des Trolls',
      slug: 'cuvee-des-trolls',
      type: 'beer',
      image_url: 'uploads/images/2320.jpeg',
      price: 1.6,
      alcohol: 7,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 24399,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Queue de Charrue Triple',
      slug: 'queue-de-charrue-triple',
      type: 'beer',
      image_url: 'uploads/images/2975.jpeg',
      price: 2,
      alcohol: 8.7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29040,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Belgoo Arboo (Triple)',
      slug: 'belgoo-arboo-triple',
      type: 'beer',
      image_url: 'uploads/images/4336.jpeg',
      price: 2.4,
      alcohol: 8.1,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28610,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bi\u00e8re du Corbeau',
      slug: 'biere-du-corbeau',
      type: 'beer',
      image_url: 'uploads/images/3772.jpeg',
      price: 2.4,
      alcohol: 9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28993,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Soft',
      slug: 'soft',
      type: 'beer',
      image_url: 'uploads/images/4307.jpeg',
      price: 1,
      alcohol: 0,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29184,
      like: false,
      dislike: false,
      comments: 0,
      name: 'mousseux',
      slug: 'mousseux',
      type: 'beer',
      price: 2,
      alcohol: 10.5,
      volume: 0.75,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28973,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Saint Feuillien triple',
      slug: 'saint-feuillien-triple',
      type: 'beer',
      image_url: 'uploads/images/4289.jpeg',
      price: 2.4,
      alcohol: 8.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22249,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Leffe Blonde',
      slug: 'leffe-blonde',
      type: 'beer',
      image_url: 'uploads/images/2313.jpeg',
      price: 1.5,
      alcohol: 6.6,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22251,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Demi Kro',
      slug: 'demi-kro',
      type: 'beer',
      image_url: 'uploads/images/2318.png',
      price: 0.7,
      alcohol: 4.5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22252,
      like: false,
      dislike: false,
      comments: 0,
      name: '1664',
      slug: '1664',
      type: 'beer',
      image_url: 'uploads/images/2319.jpeg',
      price: 1,
      alcohol: 5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22254,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Delirium Tremens',
      slug: 'delirium-tremens',
      type: 'beer',
      image_url: 'uploads/images/2321.jpeg',
      price: 2.4,
      alcohol: 9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22255,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Desperados',
      slug: 'desperados',
      type: 'beer',
      image_url: 'uploads/images/2322.jpeg',
      price: 2,
      alcohol: 5.9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22256,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Leffe Ruby',
      slug: 'leffe-ruby',
      type: 'beer',
      image_url: 'uploads/images/2323.jpeg',
      price: 1.5,
      alcohol: 4.5,
      volume: -0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22257,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Heineken',
      slug: 'heineken',
      type: 'beer',
      image_url: 'uploads/images/2324.jpeg',
      price: 1.3,
      alcohol: 5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22258,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Chimay',
      slug: 'chimay',
      type: 'beer',
      image_url: 'uploads/images/2325.jpeg',
      price: 2.2,
      alcohol: 7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22261,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Coca',
      slug: 'coca',
      type: 'beer',
      image_url: 'uploads/images/2329.jpeg',
      price: 1,
      alcohol: 0,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22262,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Corona Extra',
      slug: 'corona-extra',
      type: 'beer',
      image_url: 'uploads/images/2330.jpeg',
      price: 2,
      alcohol: 4.6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22263,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Corsendonk',
      slug: 'corsendonk',
      type: 'beer',
      image_url: 'uploads/images/2331.png',
      price: 1.8,
      alcohol: 7.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22265,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Duvel',
      slug: 'duvel',
      type: 'beer',
      image_url: 'uploads/images/2333.jpeg',
      price: 2.3,
      alcohol: 8.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22266,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Grimbergen',
      slug: 'grimbergen',
      type: 'beer',
      image_url: 'uploads/images/2334.jpeg',
      price: 1.4,
      alcohol: 6.7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22267,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Gulden draak',
      slug: 'gulden-draak',
      type: 'beer',
      image_url: 'uploads/images/2336.jpeg',
      price: 2,
      alcohol: 10.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22268,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Hoegaarden',
      slug: 'hoegaarden',
      type: 'beer',
      image_url: 'uploads/images/2337.jpeg',
      price: 1.3,
      alcohol: 4.9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22269,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Ice Tea',
      slug: 'ice-tea',
      type: 'beer',
      image_url: 'uploads/images/2338.jpeg',
      price: 1,
      alcohol: 0,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22270,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Kwak',
      slug: 'kwak',
      type: 'beer',
      image_url: 'uploads/images/2339.jpeg',
      price: 2.2,
      alcohol: 8.4,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22271,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Maredsous',
      slug: 'maredsous',
      type: 'beer',
      image_url: 'uploads/images/2340.jpeg',
      price: 2.2,
      alcohol: 6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22272,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Rince Cochon',
      slug: 'rince-cochon',
      type: 'beer',
      image_url: 'uploads/images/2341.jpeg',
      price: 2.3,
      alcohol: 8.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22273,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Schweppes',
      slug: 'schweppes',
      type: 'beer',
      image_url: 'uploads/images/2342.jpeg',
      price: 1,
      alcohol: 0,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22274,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Straffe Quadruple',
      slug: 'straffe-quadruple',
      type: 'beer',
      image_url: 'uploads/images/2343.jpeg',
      price: 2.8,
      alcohol: 11,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22276,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Vin',
      slug: 'vin',
      type: 'beer',
      image_url: 'uploads/images/2345.jpeg',
      price: 1,
      alcohol: 12,
      volume: 0.15,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22766,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Affligem',
      slug: 'affligem',
      type: 'beer',
      image_url: 'uploads/images/2762.jpeg',
      price: 1.3,
      alcohol: 4.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 22805,
      like: false,
      dislike: false,
      comments: 0,
      name: '1664 BLANCHE',
      slug: '1664-blanche',
      type: 'beer',
      image_url: 'uploads/images/2760.png',
      price: 1.4,
      alcohol: 5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23328,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Paulaner Oktoberfest',
      slug: 'paulaner-oktoberfest',
      type: 'beer',
      image_url: 'uploads/images/3032.jpeg',
      price: 3,
      alcohol: 6,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23444,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bi\u00e9rologie',
      slug: 'bierologie-1',
      type: 'beer',
      image_url: 'uploads/images/2800.png',
      price: 5,
      alcohol: 10,
      volume: 1,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23517,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Leffe',
      slug: 'pinte-leffe',
      type: 'beer',
      image_url: 'uploads/images/2809.jpeg',
      price: 2.3,
      alcohol: 6.6,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23544,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Stella',
      slug: 'pinte-stella',
      type: 'beer',
      image_url: 'uploads/images/3030.jpeg',
      price: 1.3,
      alcohol: 5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23687,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pelforth',
      slug: 'pelforth',
      type: 'beer',
      image_url: 'uploads/images/3031.jpeg',
      price: 1.4,
      alcohol: 6.5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23862,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Vin chaud',
      slug: 'vin-chaud-1',
      type: 'beer',
      image_url: 'uploads/images/2845.jpeg',
      price: 1.5,
      alcohol: 12,
      volume: 0.15,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23944,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Di\u00f4le',
      slug: 'diole',
      type: 'beer',
      image_url: 'uploads/images/3028.jpeg',
      price: 2.1,
      alcohol: 7.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 23945,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bush No\u00ebl',
      slug: 'bush-noel',
      type: 'beer',
      image_url: 'uploads/images/3029.jpeg',
      price: 1.8,
      alcohol: 12,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 26848,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Guiness',
      slug: 'guiness',
      type: 'beer',
      image_url: 'uploads/images/3754.png',
      price: 1,
      alcohol: 6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 26849,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Croque',
      slug: 'croque',
      type: 'beer',
      image_url: 'uploads/images/3320.jpeg',
      price: 1,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 27238,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pelforth Printemps',
      slug: 'pelforth-printemps',
      type: 'beer',
      image_url: 'uploads/images/3319.jpeg',
      price: 1.3,
      alcohol: 5.8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 27306,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Tigre Bock',
      slug: 'tigre-bock',
      type: 'beer',
      image_url: 'uploads/images/3276.png',
      price: 1,
      alcohol: 5.5,
      volume: 0.27,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 27394,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Cidre',
      slug: 'pinte-cidre',
      type: 'beer',
      image_url: 'uploads/images/3488.jpeg',
      price: 2.3,
      alcohol: 5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28132,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Rechargement 10\u20ac',
      slug: 'rechargement-10eu',
      type: 'beer',
      image_url: 'uploads/images/3757.jpeg',
      price: -10,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28133,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Rechargement 20\u20ac',
      slug: 'rechargement-20eu',
      type: 'beer',
      image_url: 'uploads/images/3758.png',
      price: -20,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28134,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Rechargement 30\u20ac',
      slug: 'rechargement-30eu',
      type: 'beer',
      image_url: 'uploads/images/3759.jpeg',
      price: -30,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28135,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Rechargement 40\u20ac',
      slug: 'rechargement-40eu',
      type: 'beer',
      image_url: 'uploads/images/3760.png',
      price: -40,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28497,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Grand Chlem',
      slug: 'grand-chlem',
      type: 'beer',
      image_url: 'uploads/images/4054.png',
      price: 7.6,
      alcohol: 10,
      volume: 1.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28505,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Fisher',
      slug: 'fisher',
      type: 'beer',
      image_url: 'uploads/images/3756.jpeg',
      price: 2.3,
      alcohol: 5,
      volume: 0.66,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28529,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Beer-pong',
      slug: 'beer-pong',
      type: 'beer',
      image_url: 'uploads/images/3761.jpeg',
      price: 3,
      alcohol: 4.5,
      volume: 3,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28582,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Leffe Rituel',
      slug: 'leffe-rituel',
      type: 'beer',
      image_url: 'uploads/images/3755.jpeg',
      price: 1.6,
      alcohol: 9,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28606,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bi\u00e8re du d\u00e9mon',
      slug: 'biere-du-demon',
      type: 'beer',
      image_url: 'uploads/images/3770.jpeg',
      price: 2.5,
      alcohol: 12,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28607,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Chimay Rouge',
      slug: 'chimay-rouge',
      type: 'beer',
      image_url: 'uploads/images/3771.jpeg',
      price: 2,
      alcohol: 7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28619,
      like: false,
      dislike: false,
      comments: 0,
      name: 'bouteille DVP',
      slug: 'bouteille-dvp',
      type: 'beer',
      image_url: 'uploads/images/3774.jpeg',
      price: 0.25,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28620,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte DVP',
      slug: 'pinte-dvp',
      type: 'beer',
      image_url: 'uploads/images/3775.jpeg',
      price: 1.25,
      alcohol: 4.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28623,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Quadrathlon',
      slug: 'quadrathlon',
      type: 'beer',
      image_url: 'uploads/images/3776.jpeg',
      price: 3,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28651,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pannepot',
      slug: 'pannepot',
      type: 'beer',
      image_url: 'uploads/images/3784.jpeg',
      price: 2.2,
      alcohol: 10,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28652,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Antigoon',
      slug: 'antigoon',
      type: 'beer',
      image_url: 'uploads/images/3785.jpeg',
      price: 2.2,
      alcohol: 7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28653,
      like: false,
      dislike: false,
      comments: 0,
      name: 'De Graal Quest',
      slug: 'de-graal-quest',
      type: 'beer',
      image_url: 'uploads/images/3786.jpeg',
      price: 2.2,
      alcohol: 9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28662,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Demi Cidre',
      slug: 'demi-cidre',
      type: 'beer',
      image_url: 'uploads/images/3791.jpeg',
      price: 1.2,
      alcohol: 5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28663,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Jacquie et Michel',
      slug: 'jacquie-et-michel',
      type: 'beer',
      image_url: 'uploads/images/3792.jpeg',
      price: 1.8,
      alcohol: 5.1,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28664,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Foyer coco',
      slug: 'foyer-coco',
      type: 'beer',
      price: 8,
      alcohol: 6,
      volume: 3,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28665,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Foyer coco',
      slug: 'foyer-coco-1',
      type: 'beer',
      price: 8,
      alcohol: 6,
      volume: 3,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28666,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Skoll',
      slug: 'skoll',
      type: 'beer',
      image_url: 'uploads/images/4053.jpeg',
      price: 2,
      alcohol: 6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28667,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bite de Schmutz',
      slug: 'bite-de-schmutz',
      type: 'beer',
      price: 0,
      alcohol: 10,
      volume: 0.05,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28668,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Stella Artois',
      slug: 'stella-artois',
      type: 'beer',
      image_url: 'uploads/images/4055.jpeg',
      price: 1,
      alcohol: 5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28678,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Carlsberg',
      slug: 'carlsberg',
      type: 'beer',
      image_url: 'uploads/images/3970.png',
      price: 0.9,
      alcohol: 5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28798,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Leffe Brune',
      slug: 'leffe-brune',
      type: 'beer',
      image_url: 'uploads/images/4208.jpeg',
      price: 1.4,
      alcohol: 6.6,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28809,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Kro 7.2\u00ba',
      slug: 'kro-7-2o',
      type: 'beer',
      image_url: 'uploads/images/4212.jpeg',
      price: 1.6,
      alcohol: 7.2,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28810,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Amsterdam Navigator',
      slug: 'amsterdam-navigator',
      type: 'beer',
      image_url: 'uploads/images/4213.jpeg',
      price: 2,
      alcohol: 8.4,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28811,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Amsterdam Maximator',
      slug: 'amsterdam-maximator',
      type: 'beer',
      image_url: 'uploads/images/4214.jpeg',
      price: 2,
      alcohol: 11.6,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28812,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Goudale',
      slug: 'goudale',
      type: 'beer',
      image_url: 'uploads/images/4215.jpeg',
      price: 2,
      alcohol: 7.2,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28813,
      like: false,
      dislike: false,
      comments: 0,
      name: '8.6 Original',
      slug: '8-6-original',
      type: 'beer',
      image_url: 'uploads/images/4216.png',
      price: 1.6,
      alcohol: 8.6,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28814,
      like: false,
      dislike: false,
      comments: 0,
      name: '8.6 Extreme',
      slug: '8-6-extreme',
      type: 'beer',
      image_url: 'uploads/images/4217.png',
      price: 2,
      alcohol: 10.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28815,
      like: false,
      dislike: false,
      comments: 0,
      name: '8.6 Red',
      slug: '8-6-red',
      type: 'beer',
      image_url: 'uploads/images/4218.jpeg',
      price: 1.9,
      alcohol: 7.9,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28816,
      like: false,
      dislike: false,
      comments: 0,
      name: '8.6 Gold',
      slug: '8-6-gold',
      type: 'beer',
      image_url: 'uploads/images/4219.jpeg',
      price: 1.9,
      alcohol: 6.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28817,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Chouffe',
      slug: 'pinte-chouffe',
      type: 'beer',
      image_url: 'uploads/images/4220.jpeg',
      price: 3.5,
      alcohol: 8,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28828,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte kro sans subvention',
      slug: 'pinte-kro-sans-subvention',
      type: 'beer',
      image_url: 'uploads/images/4223.png',
      price: 2,
      alcohol: 4.2,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28842,
      like: false,
      dislike: false,
      comments: 0,
      name: "Cuv\u00e9e Blizz'Art",
      slug: 'cuvee-blizz-art',
      type: 'beer',
      image_url: 'uploads/images/4226.jpeg',
      price: 2,
      alcohol: 5.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28847,
      like: false,
      dislike: false,
      comments: 0,
      name: "Demi blizz'art",
      slug: 'demi-blizz-art',
      type: 'beer',
      price: 1,
      alcohol: 5.2,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28848,
      like: false,
      dislike: false,
      comments: 0,
      name: "Demi blizz'art",
      slug: 'demi-blizz-art-1',
      type: 'beer',
      price: 1,
      alcohol: 5.2,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28857,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Triple K',
      slug: 'pinte-triple-k',
      type: 'beer',
      image_url: 'uploads/images/4241.png',
      price: 3.5,
      alcohol: 8.4,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28858,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Chouffe',
      slug: 'pinte-chouffe-1',
      type: 'beer',
      price: 3.5,
      alcohol: 8,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28893,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Leffe blonde 33',
      slug: 'leffe-blonde-33',
      type: 'beer',
      image_url: 'uploads/images/4250.jpeg',
      price: 1.7,
      alcohol: 6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28896,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bouteille Champagne',
      slug: 'bouteille-champagne',
      type: 'beer',
      image_url: 'uploads/images/4294.jpeg',
      price: 1000,
      alcohol: 12,
      volume: 0.75,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28946,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Hot-dogs',
      slug: 'hot-dogs',
      type: 'beer',
      image_url: 'uploads/images/4279.jpeg',
      price: 0.5,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28969,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Queue de charrue Ambr\u00e9e',
      slug: 'queue-de-charrue-ambree',
      type: 'beer',
      image_url: 'uploads/images/4285.jpeg',
      price: 1.7,
      alcohol: 5.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28974,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Trappe triple',
      slug: 'trappe-triple',
      type: 'beer',
      image_url: 'uploads/images/4290.png',
      price: 2.4,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28975,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Lindemans Faro',
      slug: 'lindemans-faro',
      type: 'beer',
      image_url: 'uploads/images/4291.png',
      price: 1.8,
      alcohol: 4.2,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28984,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Mordue',
      slug: 'mordue',
      type: 'beer',
      image_url: 'uploads/images/4298.jpeg',
      price: 1.5,
      alcohol: 6,
      volume: 0.28,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28986,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Jambe de bois',
      slug: 'jambe-de-bois',
      type: 'beer',
      image_url: 'uploads/images/4300.png',
      price: 2.3,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28988,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Val Dieu',
      slug: 'val-dieu',
      type: 'beer',
      image_url: 'uploads/images/4302.png',
      price: 2.4,
      alcohol: 9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28990,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Type Eau',
      slug: 'type-eau',
      type: 'beer',
      image_url: 'uploads/images/4304.jpeg',
      price: 9.6,
      alcohol: 7,
      volume: 1.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28991,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Type Feu',
      slug: 'type-feu',
      type: 'beer',
      image_url: 'uploads/images/4305.jpeg',
      price: 6.4,
      alcohol: 7,
      volume: 1.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28992,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Type Plante',
      slug: 'type-plante',
      type: 'beer',
      image_url: 'uploads/images/4306.jpeg',
      price: 10.6,
      alcohol: 7,
      volume: 1.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 28994,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Trappe quadruple',
      slug: 'trappe-quadruple',
      type: 'beer',
      image_url: 'uploads/images/4308.jpeg',
      price: 2.7,
      alcohol: 10,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29004,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Lamoral',
      slug: 'lamoral',
      type: 'beer',
      image_url: 'uploads/images/4313.png',
      price: 2.4,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29005,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Viven IPA',
      slug: 'viven-ipa',
      type: 'beer',
      image_url: 'uploads/images/4314.jpeg',
      price: 2.4,
      alcohol: 7,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29006,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Saint Louis Gueuze',
      slug: 'saint-louis-gueuze',
      type: 'beer',
      image_url: 'uploads/images/4315.png',
      price: 1.5,
      alcohol: 4.5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29007,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Chouffe Houblon IPA',
      slug: 'chouffe-houblon-ipa',
      type: 'beer',
      image_url: 'uploads/images/4316.jpeg',
      price: 2.6,
      alcohol: 9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29020,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bouteille Cidre Prestige',
      slug: 'bouteille-cidre-prestige',
      type: 'beer',
      image_url: 'uploads/images/4320.png',
      price: 4,
      alcohol: 6,
      volume: 0.75,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29022,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Monaco',
      slug: 'monaco',
      type: 'beer',
      image_url: 'uploads/images/4324.png',
      price: 1.15,
      alcohol: 4.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29023,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Monaco',
      slug: 'monaco-1',
      type: 'beer',
      image_url: 'uploads/images/4321.jpeg',
      price: 1.15,
      alcohol: 4.5,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29024,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Kerisac 25 cL',
      slug: 'kerisac-25-cl',
      type: 'beer',
      image_url: 'uploads/images/4322.jpeg',
      price: 1.5,
      alcohol: 4.5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29025,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Kerisac 25 cL',
      slug: 'kerisac-25-cl-1',
      type: 'beer',
      image_url: 'uploads/images/4323.jpeg',
      price: 1.5,
      alcohol: 4.5,
      volume: 0.25,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29039,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Paix-Dieu',
      slug: 'paix-dieu',
      type: 'beer',
      image_url: 'uploads/images/4335.jpeg',
      price: 2.8,
      alcohol: 10,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29043,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Flute de champagne',
      slug: 'flute-de-champagne',
      type: 'beer',
      image_url: 'uploads/images/4345.jpeg',
      price: 1.5,
      alcohol: 11,
      volume: 0.12,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29044,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Champagne 75cL',
      slug: 'champagne-75cl',
      type: 'beer',
      image_url: 'uploads/images/4346.jpeg',
      price: 2,
      alcohol: 11,
      volume: 0.75,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29045,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Fl\u00fbte en plastique',
      slug: 'flute-en-plastique',
      type: 'beer',
      image_url: 'uploads/images/4347.jpeg',
      price: 0.5,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29072,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Grimbergen Blanche',
      slug: 'pinte-grimbergen-blanche',
      type: 'beer',
      image_url: 'uploads/images/4588.jpeg',
      price: 3.5,
      alcohol: 6,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29095,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bi\u00e8res panier',
      slug: 'bieres-panier',
      type: 'beer',
      image_url: 'uploads/images/4630.png',
      price: 2.5,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29099,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Morto de mes couilles',
      slug: 'morto-de-mes-couilles',
      type: 'beer',
      image_url: 'uploads/images/4636.jpeg',
      price: 1,
      alcohol: 0,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29106,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Goudale',
      slug: 'pinte-goudale',
      type: 'beer',
      image_url: 'uploads/images/4643.png',
      price: 2.9,
      alcohol: 7.2,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29147,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pinte Grimbergen Triple',
      slug: 'pinte-grimbergen-triple',
      type: 'beer',
      image_url: 'uploads/images/4651.png',
      price: 4.2,
      alcohol: 9,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29148,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Goudale 33cL',
      slug: 'goudale-33cl',
      type: 'beer',
      image_url: 'uploads/images/4652.jpeg',
      price: 2,
      alcohol: 7.6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29153,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Tongerlo Prior',
      slug: 'tongerlo-prior',
      type: 'beer',
      image_url: 'uploads/images/4655.jpeg',
      price: 2.5,
      alcohol: 9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29158,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Kasteel Blonde',
      slug: 'kasteel-blonde',
      type: 'beer',
      image_url: 'uploads/images/4656.jpeg',
      price: 2,
      alcohol: 8,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29163,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Carlsberg Elephant',
      slug: 'carlsberg-elephant',
      type: 'beer',
      image_url: 'uploads/images/4657.jpeg',
      price: 2,
      alcohol: 7.2,
      volume: 0.5,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29166,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Bolossage de trez',
      slug: 'bolossage-de-trez',
      type: 'beer',
      image_url: 'uploads/images/4659.jpeg',
      price: 0,
      alcohol: 13,
      volume: -0.13,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29170,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Sex-gen performant',
      slug: 'sex-gen-performant',
      type: 'beer',
      image_url: 'uploads/images/4663.jpeg',
      price: 0,
      alcohol: 10,
      volume: 0,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29172,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Westmalle Triple',
      slug: 'westmalle-triple',
      type: 'beer',
      image_url: 'uploads/images/4666.jpeg',
      price: 2.5,
      alcohol: 9.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29174,
      like: false,
      dislike: false,
      comments: 0,
      name: 'BEAU PORTE-CHARGES',
      slug: 'beau-porte-charges',
      type: 'beer',
      image_url: 'uploads/images/4667.jpeg',
      price: 0,
      alcohol: 15,
      volume: 85,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29186,
      like: false,
      dislike: false,
      comments: 0,
      name: 'La G de Goudale',
      slug: 'la-g-de-goudale',
      type: 'beer',
      image_url: 'uploads/images/4673.jpeg',
      price: 2.5,
      alcohol: 7.9,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29187,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Parisis Blanche',
      slug: 'parisis-blanche',
      type: 'beer',
      image_url: 'uploads/images/4674.png',
      price: 2.7,
      alcohol: 4.1,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29188,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Pietra',
      slug: 'pietra',
      type: 'beer',
      image_url: 'uploads/images/4675.jpeg',
      price: 2.3,
      alcohol: 6,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29195,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Trappe Blonde',
      slug: 'trappe-blonde',
      type: 'beer',
      price: 2.2,
      alcohol: 6.5,
      volume: 0.33,
    },
    {
      likes: 0,
      dislikes: 0,
      id: 29196,
      like: false,
      dislike: false,
      comments: 0,
      name: 'Trappiste Rocheford',
      slug: 'trappiste-rocheford',
      type: 'beer',
      price: 2.8,
      alcohol: 9.8,
      volume: 0.33,
    },
  ],
});

function drinksPageReducer(state = initialState, action) {
  switch (action.type) {
    case DEFAULT_ACTION:
      return state;
    default:
      return state;
  }
}

export default drinksPageReducer;
