// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency_injection

import (
	"github.com/LouisTrezzini/foyer.enpc.org/app/services"
)

// Injectors from initialize.go:

func initializeContainer() (Container, error) {
	connection, err := NewBongoConnection()
	if err != nil {
		return Container{}, err
	}
	accountRepositoryBongo := &services.AccountRepositoryBongo{
		Connection: connection,
	}
	drinkRepositoryInMemory := services.NewDrinkRepositoryInMemory()
	foyerServiceImpl := &services.FoyerServiceImpl{
		AccountRepository: accountRepositoryBongo,
		DrinkRepository:   drinkRepositoryInMemory,
	}
	dependency_injectionContainer := Container{
		AccountRepository: accountRepositoryBongo,
		DrinkRepository:   drinkRepositoryInMemory,
		FoyerService:      foyerServiceImpl,
	}
	return dependency_injectionContainer, nil
}
