/*
 *
 * TransactionsPage reducer
 *
 */

import { fromJS } from 'immutable';
import { DEFAULT_ACTION } from './constants';

export const initialState = fromJS({
  transactions: [
    {
      id: 43358,
      date: 1548374548,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43359,
      date: 1548374548,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43356,
      date: 1548374547,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43357,
      date: 1548374547,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43355,
      date: 1548374423,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'pauline.hubert',
        email: 'pauline.hubert@eleves.enpc.fr',
        image_url: 'uploads/images/4432.jpeg',
        nick: 'Pauline Hubert',
        first_name: 'Pauline',
        last_name: 'Hubert',
        gender: 'F',
        promo: '021',
        department: '1A',
        origin: 'AST',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 10,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43354,
      date: 1548374402,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'sixtine.dunglas',
        email: 'sixtine.dunglas@eleves.enpc.fr',
        image_url: 'uploads/images/4351.jpeg',
        nick: 'Sixtine Dunglas',
        first_name: 'Sixtine',
        last_name: 'Dunglas',
        gender: 'F',
        promo: '020',
        department: 'GMM',
        origin: 'Concours Commun',
        location: 'Meunier 314',
        phone: '0633394331',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -5.8,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43353,
      date: 1548374165,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'sixtine.dunglas',
        email: 'sixtine.dunglas@eleves.enpc.fr',
        image_url: 'uploads/images/4351.jpeg',
        nick: 'Sixtine Dunglas',
        first_name: 'Sixtine',
        last_name: 'Dunglas',
        gender: 'F',
        promo: '020',
        department: 'GMM',
        origin: 'Concours Commun',
        location: 'Meunier 314',
        phone: '0633394331',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -5.8,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43352,
      date: 1548374023,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'thibaut.bourdais',
        email: 'thibaut.bourdais@eleves.enpc.fr',
        image_url: 'uploads/images/3873.jpeg',
        nick: 'Thibaut Bourdais',
        first_name: 'Thibaut',
        last_name: 'Bourdais',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        phone: '0632779748',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -10.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43351,
      date: 1548373908,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'romain.wenzel',
        email: 'romain.wenzel@eleves.enpc.fr',
        image_url: 'uploads/images/4548.jpeg',
        nick: 'Romain Wenzel',
        first_name: 'Romain',
        last_name: 'Wenzel',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        phone: '0627419195',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 9.4,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43350,
      date: 1548373850,
      amount: -2,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 24399,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Queue de Charrue Triple',
        slug: 'queue-de-charrue-triple',
        type: 'beer',
        image_url: 'uploads/images/2975.jpeg',
        price: 2,
        alcohol: 8.7,
        volume: 0.33,
      },
      user: {
        username: 'romain.tui',
        email: 'romain.tui@eleves.enpc.fr',
        image_url: 'uploads/images/4682.jpeg',
        nick: 'Romain Tui',
        first_name: 'Romain',
        last_name: 'Tui',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier 252',
        phone: '0665127967',
        skype: 'romishouuu',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 20.8,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43349,
      date: 1548373817,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'antoine.wolff1',
        email: 'antoine.wolff1@eleves.enpc.fr',
        image_url: 'uploads/images/3913.jpeg',
        nick: 'Wolff',
        first_name: 'Antoine',
        last_name: 'Wolff',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Perro zoo',
        phone: '0620319283',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 4.7,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43348,
      date: 1548373791,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'loris.andre',
        email: 'loris.andre@eleves.enpc.fr',
        image_url: 'uploads/images/3864.jpeg',
        nick: 'Loris Andr\u00e9',
        first_name: 'Loris',
        last_name: 'Andr\u00e9',
        gender: 'M',
        promo: '020',
        department: 'SEGF',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -8.7,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43347,
      date: 1548373762,
      amount: -3.4,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 29169,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Carlsberg',
        slug: 'pinte-carlsberg',
        type: 'beer',
        image_url: 'uploads/images/4662.jpeg',
        price: 3.4,
        alcohol: 5,
        volume: 0.5,
      },
      user: {
        username: 'arnaud.lafargue',
        email: 'arnaud.lafargue@eleves.enpc.fr',
        image_url: 'uploads/images/4376.jpeg',
        nick: 'Arnaud Lafargue',
        first_name: 'Arnaud',
        last_name: 'Lafargue',
        gender: 'M',
        promo: '020',
        department: 'GI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: '216',
        phone: '0614058352',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 1.5,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43346,
      date: 1548373722,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'vincent.horent',
        email: 'vincent.horent@eleves.enpc.fr',
        image_url: 'uploads/images/4683.jpeg',
        nick: 'Plaid',
        first_name: 'Vincent',
        last_name: 'Horent',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: false,
        balance: 0.2,
        mail_event: true,
        mail_modification: false,
        mail_shotgun: false,
      },
    },
    {
      id: 43345,
      date: 1548373688,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'adrien.cotil',
        email: 'adrien.cotil@eleves.enpc.fr',
        image_url: 'uploads/images/3916.jpeg',
        nick: 'Adrien Cotil',
        first_name: 'Adrien',
        last_name: 'Cotil',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 1.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43344,
      date: 1548373628,
      amount: -2.4,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 29040,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Belgoo Arboo (Triple)',
        slug: 'belgoo-arboo-triple',
        type: 'beer',
        image_url: 'uploads/images/4336.jpeg',
        price: 2.4,
        alcohol: 8.1,
        volume: 0.33,
      },
      user: {
        username: 'agathe.chevallier',
        email: 'agathe.chevallier@eleves.enpc.fr',
        image_url: 'uploads/images/3959.jpeg',
        nick: 'Agathe Chevallier',
        first_name: 'Agathe',
        last_name: 'Chevallier',
        gender: 'F',
        promo: '020',
        department: 'GCC',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 24.5,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43343,
      date: 1548373596,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'regis.santet',
        email: 'regis.santet@eleves.enpc.fr',
        image_url: 'uploads/images/4269.png',
        nick: 'R\u00e9gis Santet',
        first_name: 'R\u00e9gis',
        last_name: 'Santet',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: '\u0152noloc',
        phone: '0681884146',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 11.6,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43342,
      date: 1548373452,
      amount: -3.4,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 29169,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Carlsberg',
        slug: 'pinte-carlsberg',
        type: 'beer',
        image_url: 'uploads/images/4662.jpeg',
        price: 3.4,
        alcohol: 5,
        volume: 0.5,
      },
      user: {
        username: 'valentine.hure',
        email: 'valentine.hure@eleves.enpc.fr',
        image_url: 'uploads/images/3890.jpeg',
        nick: 'Valentine Hur\u00e9',
        first_name: 'Valentine',
        last_name: 'Hur\u00e9',
        gender: 'F',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 16.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43341,
      date: 1548373382,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43340,
      date: 1548373349,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'ana-maria.gonzalez-quintero',
        email: 'ana-maria.gonzalez-quintero@eleves.enpc.fr',
        image_url: 'uploads/images/4627.jpeg',
        nick: 'Ana Maria Gonzalez Quintero',
        first_name: 'Ana Maria',
        last_name: 'Gonzalez Quintero',
        gender: 'F',
        promo: '020',
        department: 'GI',
        origin: 'Double Dipl\u00f4me',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -1.05,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43337,
      date: 1548373307,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'younes.lotfi',
        email: 'younes.lotfi@eleves.enpc.fr',
        image_url: 'uploads/images/4512.jpeg',
        nick: 'Youn\u00e8s Lotfi',
        first_name: 'Youn\u00e8s',
        last_name: 'Lotfi',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        location: 'Meunier 313',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -4.7,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43338,
      date: 1548373307,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'antoine.wolff1',
        email: 'antoine.wolff1@eleves.enpc.fr',
        image_url: 'uploads/images/3913.jpeg',
        nick: 'Wolff',
        first_name: 'Antoine',
        last_name: 'Wolff',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Perro zoo',
        phone: '0620319283',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 4.7,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43339,
      date: 1548373307,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'thibaut.bourdais',
        email: 'thibaut.bourdais@eleves.enpc.fr',
        image_url: 'uploads/images/3873.jpeg',
        nick: 'Thibaut Bourdais',
        first_name: 'Thibaut',
        last_name: 'Bourdais',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        phone: '0632779748',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -10.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43336,
      date: 1548373260,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'lucas.wartelle',
        email: 'lucas.wartelle@eleves.enpc.fr',
        image_url: 'uploads/images/4427.jpeg',
        nick: 'lukwrt',
        first_name: 'Lucas',
        last_name: 'Wartelle',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: '131 Meunierzer',
        phone: '0778695464',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 4.2,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43335,
      date: 1548373163,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'david.boudin',
        email: 'david.boudin@eleves.enpc.fr',
        image_url: 'uploads/images/3872.jpeg',
        nick: 'Davboud',
        first_name: 'David',
        last_name: 'Boudin',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        nationality: 'Japon',
        location: '305',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 8.55,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43334,
      date: 1548373068,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'jean-christophe.schmitt',
        email: 'jean-christophe.schmitt@eleves.enpc.fr',
        image_url: 'uploads/images/3906.jpeg',
        nick: 'Jean-Christophe Schmitt',
        first_name: 'Jean-Christophe',
        last_name: 'Schmitt',
        gender: 'M',
        promo: '020',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        phone: '0677027143',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 19.65,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43333,
      date: 1548373024,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'arnaud.lafargue',
        email: 'arnaud.lafargue@eleves.enpc.fr',
        image_url: 'uploads/images/4376.jpeg',
        nick: 'Arnaud Lafargue',
        first_name: 'Arnaud',
        last_name: 'Lafargue',
        gender: 'M',
        promo: '020',
        department: 'GI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: '216',
        phone: '0614058352',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 1.5,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43332,
      date: 1548373023,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'thomas.giovagnoli',
        email: 'thomas.giovagnoli@eleves.enpc.fr',
        image_url: 'uploads/images/3950.jpeg',
        nick: 'Thomas Giovagnoli',
        first_name: 'Thomas',
        last_name: 'Giovagnoli',
        gender: 'M',
        promo: '020',
        department: 'VET',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -3.5,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43331,
      date: 1548372901,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'max.castello',
        email: 'max.castello@eleves.enpc.fr',
        image_url: 'uploads/images/4587.jpeg',
        nick: 'Max Castello',
        first_name: 'Max',
        last_name: 'Castello',
        gender: 'M',
        promo: '019',
        department: 'GCC',
        origin: 'Stagiaire',
        nationality: 'France',
        phone: '0666702190',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 5.9,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43330,
      date: 1548372883,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'javier.espada-fraile',
        email: 'javier.espada-fraile@eleves.enpc.fr',
        image_url: 'uploads/others/default-user.png',
        nick: 'Javier Espada Fraile',
        first_name: 'Javier',
        last_name: 'Espada Fraile',
        gender: 'M',
        promo: '020',
        department: 'GCC',
        origin: 'Double Dipl\u00f4me',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 53.3,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43329,
      date: 1548372865,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'claire.benedetti',
        email: 'claire.benedetti@eleves.enpc.fr',
        image_url: 'uploads/images/4449.jpeg',
        nick: 'Claire Benedetti',
        first_name: 'Claire',
        last_name: 'Benedetti',
        gender: 'F',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -0.95,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43328,
      date: 1548372836,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'jon.vadillo-fernandez',
        email: 'jon.vadillo-fernandez@eleves.enpc.fr',
        image_url: 'uploads/images/4577.jpeg',
        nick: 'Jon Vadillo Fernandez',
        first_name: 'Jon',
        last_name: 'Vadillo Fernandez',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 7.2,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43327,
      date: 1548372805,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'cleo.pouchin-chemin',
        email: 'cleo.pouchin-chemin@eleves.enpc.fr',
        image_url: 'uploads/images/4528.jpeg',
        nick: 'Cl\u00e9o Pouchin Chemin',
        first_name: 'Cl\u00e9o',
        last_name: 'Pouchin Chemin',
        gender: 'F',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier (329)',
        phone: '0788424413',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -18.3,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43325,
      date: 1548372804,
      amount: -3.4,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 29169,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Carlsberg',
        slug: 'pinte-carlsberg',
        type: 'beer',
        image_url: 'uploads/images/4662.jpeg',
        price: 3.4,
        alcohol: 5,
        volume: 0.5,
      },
      user: {
        username: 'valentine.hure',
        email: 'valentine.hure@eleves.enpc.fr',
        image_url: 'uploads/images/3890.jpeg',
        nick: 'Valentine Hur\u00e9',
        first_name: 'Valentine',
        last_name: 'Hur\u00e9',
        gender: 'F',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 16.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43326,
      date: 1548372804,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'romain.chaffanjon',
        email: 'romain.chaffanjon@eleves.enpc.fr',
        image_url: 'uploads/images/4467.jpeg',
        nick: 'Romain Chaffanjon',
        first_name: 'Romain',
        last_name: 'Chaffanjon',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 17.8,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43324,
      date: 1548372746,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'liam.gonzalez',
        email: 'liam.gonzalez@eleves.enpc.fr',
        image_url: 'uploads/others/default-user.png',
        nick: 'Liam Gonzalez',
        first_name: 'Liam',
        last_name: 'Gonzalez',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 10.6,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43323,
      date: 1548372732,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'jb.sallenave',
        email: 'jean-baptiste.sallenave@eleves.enpc.fr',
        image_url: 'uploads/images/4430.jpeg',
        nick: 'Jean-Baptiste Sallenave',
        first_name: 'Jean-Baptiste',
        last_name: 'Sallenave',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -7.95,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43322,
      date: 1548372707,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'jb.sallenave',
        email: 'jean-baptiste.sallenave@eleves.enpc.fr',
        image_url: 'uploads/images/4430.jpeg',
        nick: 'Jean-Baptiste Sallenave',
        first_name: 'Jean-Baptiste',
        last_name: 'Sallenave',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -7.95,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43321,
      date: 1548372653,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'julia.linhart',
        email: 'julia.linhart@eleves.enpc.fr',
        image_url: 'uploads/images/3895.jpeg',
        nick: 'Julia Linhart',
        first_name: 'Julia',
        last_name: 'Linhart',
        gender: 'F',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 2.7,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43320,
      date: 1548372633,
      amount: -1.6,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22253,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Cuv\u00e9e des Trolls',
        slug: 'cuvee-des-trolls',
        type: 'beer',
        image_url: 'uploads/images/2320.jpeg',
        price: 1.6,
        alcohol: 7,
        volume: 0.25,
      },
      user: {
        username: 'adrien.cotil',
        email: 'adrien.cotil@eleves.enpc.fr',
        image_url: 'uploads/images/3916.jpeg',
        nick: 'Adrien Cotil',
        first_name: 'Adrien',
        last_name: 'Cotil',
        gender: 'M',
        promo: '020',
        department: 'IMI',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 1.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43319,
      date: 1548372632,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'sixtine.lauron',
        email: 'sixtine.lauron@eleves.enpc.fr',
        image_url: 'uploads/images/4162.png',
        nick: 'Sixtine Lauron',
        first_name: 'Sixtine',
        last_name: 'Lauron',
        gender: 'F',
        promo: '020',
        department: 'GI',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 2,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43318,
      date: 1548372572,
      amount: -1,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22248,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Pinte Kro',
        slug: 'pinte-kro',
        type: 'beer',
        image_url: 'uploads/images/2315.jpeg',
        price: 1,
        alcohol: 4.5,
        volume: 0.5,
      },
      user: {
        username: 'gregoire.lambert',
        email: 'gregoire.lambert@eleves.enpc.fr',
        image_url: 'uploads/images/4566.jpeg',
        nick: 'Gr\u00e9goire Lambert',
        first_name: 'Gr\u00e9goire',
        last_name: 'Lambert',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43317,
      date: 1548372490,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'ana-maria.gonzalez-quintero',
        email: 'ana-maria.gonzalez-quintero@eleves.enpc.fr',
        image_url: 'uploads/images/4627.jpeg',
        nick: 'Ana Maria Gonzalez Quintero',
        first_name: 'Ana Maria',
        last_name: 'Gonzalez Quintero',
        gender: 'F',
        promo: '020',
        department: 'GI',
        origin: 'Double Dipl\u00f4me',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -1.05,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43315,
      date: 1548372435,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'baptiste.grignola',
        email: 'baptiste.grignola@eleves.enpc.fr',
        image_url: 'uploads/images/3931.jpeg',
        nick: 'Baptiste Grignola',
        first_name: 'Baptiste',
        last_name: 'Grignola',
        gender: 'M',
        promo: '020',
        department: 'SEGF',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -6.3,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43314,
      date: 1548372395,
      amount: -2.3,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22275,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Triple Karmeliet',
        slug: 'triple-karmeliet',
        type: 'beer',
        image_url: 'uploads/images/2344.jpeg',
        price: 2.3,
        alcohol: 8.4,
        volume: 0.33,
      },
      user: {
        username: 'paula-sofia.carvajal-sanchez',
        email: 'paula-sofia.carvajal-sanchez@eleves.enpc.fr',
        image_url: 'uploads/others/default-user.png',
        nick: 'Paula Sofia Carvajal Sanchez',
        first_name: 'Paula Sofia',
        last_name: 'Carvajal Sanchez',
        gender: 'F',
        promo: '020',
        department: 'GI',
        origin: 'Double Dipl\u00f4me',
        nationality: 'Autre',
        location: 'Champs-sur-marne, 77420',
        phone: '0782989320',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -2.3,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43313,
      date: 1548372301,
      amount: -2,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 28971,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Saint Bernardus Triple',
        slug: 'saint-bernardus-triple',
        type: 'beer',
        image_url: 'uploads/images/4287.png',
        price: 2,
        alcohol: 8,
        volume: 0.33,
      },
      user: {
        username: 'gregoire.archambeaud',
        email: 'gregoire.archambeaud@eleves.enpc.fr',
        image_url: 'uploads/images/4551.jpeg',
        nick: 'Don Grego',
        first_name: 'Gr\u00e9goire',
        last_name: 'Archambeaud',
        gender: 'M',
        promo: '021',
        department: '1A',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'Meunier',
        phone: '0661013546',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 6.1,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43312,
      date: 1548372223,
      amount: -1.6,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 22253,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Cuv\u00e9e des Trolls',
        slug: 'cuvee-des-trolls',
        type: 'beer',
        image_url: 'uploads/images/2320.jpeg',
        price: 1.6,
        alcohol: 7,
        volume: 0.25,
      },
      user: {
        username: 'nicolas.royet',
        email: 'nicolas.royet@eleves.enpc.fr',
        image_url: 'uploads/images/3835.jpeg',
        nick: 'Nicolas Royet',
        first_name: 'Nicolas',
        last_name: 'Royet',
        gender: 'M',
        promo: '020',
        department: 'GMM',
        origin: 'Concours Commun',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: 2.3,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43308,
      date: 1548372152,
      amount: -2,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 24399,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Queue de Charrue Triple',
        slug: 'queue-de-charrue-triple',
        type: 'beer',
        image_url: 'uploads/images/2975.jpeg',
        price: 2,
        alcohol: 8.7,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43309,
      date: 1548372152,
      amount: -2,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 24399,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Queue de Charrue Triple',
        slug: 'queue-de-charrue-triple',
        type: 'beer',
        image_url: 'uploads/images/2975.jpeg',
        price: 2,
        alcohol: 8.7,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
    {
      id: 43310,
      date: 1548372152,
      amount: -2,
      beer: {
        likes: 0,
        dislikes: 0,
        id: 24399,
        like: false,
        dislike: false,
        comments: 0,
        name: 'Queue de Charrue Triple',
        slug: 'queue-de-charrue-triple',
        type: 'beer',
        image_url: 'uploads/images/2975.jpeg',
        price: 2,
        alcohol: 8.7,
        volume: 0.33,
      },
      user: {
        username: 'gabriel.plantier',
        email: 'gabriel.plantier@eleves.enpc.fr',
        image_url: 'uploads/images/3458.jpeg',
        nick: 'Gabriel Plantier',
        first_name: 'Gabriel',
        last_name: 'Plantier',
        gender: 'M',
        promo: '019',
        department: 'SEGF',
        origin: 'Concours Commun',
        nationality: 'France',
        location: 'meunier',
        phone: '0603861699',
        tour: true,
        stats_foyer: true,
        stats_ponthub: true,
        stats_facegame: true,
        balance: -25.29,
        mail_event: true,
        mail_modification: true,
        mail_shotgun: true,
      },
    },
  ],
});

function transactionsPageReducer(state = initialState, action) {
  switch (action.type) {
    case DEFAULT_ACTION:
      return state;
    default:
      return state;
  }
}

export default transactionsPageReducer;
